sudo: required

language: javascript

services:
  - docker
  
script:
  - docker build -t naffiq/naffiq-com .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push naffiq/naffiq-com;
    fi