name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: v10.*
    - name: Install node dependencies
      run: npm i
    - name: Build gatsby
      run: npm run build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@master
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
